### ISSUE TITLE
SnailQuickMaskPopups被释放，添加的tap手势将会失效

### ISSUE THREAD

**Issue by gaoshilei** [snail-z/SnailPopupController#2]
创建视图完成之后，SnailQuickMaskPopups如果没有被引用将会被释放，popups还是可以正常显示的，但是这个时候关闭popups的手势tap的target为空，手势失效。可否考虑将SnailQuickMaskPopups写成单例

**Comment by snail-z** [comment]
您好，局部创建SnailQuickMaskPopups确实是有这个问题的，可以声明为全局属性使其不被释放。
另外，最新版本已更新，更加简洁方便。欢迎使用！
